mod commands;
mod db;
mod error;
mod markdown;

use commands::AppState;
use tauri::Manager;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .setup(|app| {
            let path = db::default_db_path()?;
            let pool = tauri::async_runtime::block_on(db::open_pool(&path))?;
            app.manage(AppState { pool });
            Ok(())
        })
        .invoke_handler(tauri::generate_handler![
            commands::lists::list_today,
            commands::lists::list_by_id,
            commands::lists::list_all,
            commands::lists::create_list,
            commands::lists::rename_list,
            commands::lists::archive_list,
            commands::lists::restore_list,
            commands::lists::set_list_pinned,
            commands::todos::list_todos,
            commands::todos::create_todo,
            commands::todos::update_todo,
            commands::todos::toggle_todo,
            commands::todos::delete_todo,
            commands::todos::reorder_todos,
            commands::tags::list_tags,
            commands::tags::tags_for_todo,
            commands::tags::add_tag_to_todo,
            commands::tags::remove_tag_from_todo,
            commands::export::export_list_md,
            commands::export::export_range_md,
            commands::export::save_text_file,
            commands::export::save_binary_file,
            commands::search::search_todos,
            commands::search::list_all_todos,
            commands::search::get_stats,
            commands::search::get_daily_stats,
            commands::search::get_weekly_activity,
            commands::workflows::list_workflows,
            commands::workflows::workflow_by_id,
            commands::workflows::create_workflow,
            commands::workflows::rename_workflow,
            commands::workflows::update_workflow_description,
            commands::workflows::delete_workflow,
            commands::workflows::set_workflow_pinned,
            commands::workflows::set_workflow_archived,
            commands::workflows::list_workflow_steps,
            commands::workflows::create_workflow_step,
            commands::workflows::update_workflow_step,
            commands::workflows::delete_workflow_step,
            commands::workflows::reorder_workflow_steps,
            commands::notes::list_notes,
            commands::notes::list_notes_for_date,
            commands::notes::note_by_id,
            commands::notes::create_note,
            commands::notes::rename_note,
            commands::notes::update_note_body,
            commands::notes::delete_note,
            commands::notes::set_note_pinned,
            commands::notes::set_note_archived,
            commands::notes::get_index_doc,
            commands::notes::update_index_doc,
            commands::articles::list_articles,
            commands::articles::article_by_id,
            commands::articles::create_article,
            commands::articles::rename_article,
            commands::articles::update_article_body,
            commands::articles::delete_article,
            commands::articles::set_article_pinned,
            commands::articles::set_article_archived,
            commands::map::get_map,
            commands::map::add_map_node,
            commands::map::add_map_text,
            commands::map::add_map_comment,
            commands::map::add_map_custom,
            commands::map::add_map_title,
            commands::map::resize_map_node,
            commands::map::update_map_node_content,
            commands::map::move_map_node,
            commands::map::remove_map_node,
            commands::map::add_map_edge,
            commands::map::update_map_edge_label,
            commands::map::remove_map_edge,
            commands::feedback::list_feedback_boards,
            commands::feedback::create_feedback_board,
            commands::feedback::rename_feedback_board,
            commands::feedback::set_feedback_board_archived,
            commands::feedback::set_feedback_board_pinned,
            commands::feedback::delete_feedback_board,
            commands::feedback::list_feedback_columns,
            commands::feedback::create_feedback_column,
            commands::feedback::rename_feedback_column,
            commands::feedback::delete_feedback_column,
            commands::feedback::list_feedback_cards,
            commands::feedback::create_feedback_card,
            commands::feedback::update_feedback_card,
            commands::feedback::set_feedback_card_color,
            commands::feedback::move_feedback_card,
            commands::feedback::delete_feedback_card,
            commands::feedback::list_feedback_card_comments,
            commands::feedback::add_feedback_card_comment,
            commands::feedback::delete_feedback_card_comment,
            commands::flashcards::list_flashcard_categories,
            commands::flashcards::create_flashcard_category,
            commands::flashcards::update_flashcard_category,
            commands::flashcards::delete_flashcard_category,
            commands::flashcards::list_flashcards,
            commands::flashcards::flashcard_by_id,
            commands::flashcards::create_flashcard,
            commands::flashcards::update_flashcard,
            commands::flashcards::set_flashcard_category,
            commands::flashcards::set_flashcard_color,
            commands::flashcards::set_flashcard_emoji,
            commands::flashcards::set_flashcard_image,
            commands::flashcards::set_flashcard_pinned,
            commands::flashcards::set_flashcard_archived,
            commands::flashcards::move_flashcard,
            commands::flashcards::delete_flashcard,
            commands::images::save_image,
            commands::blueprints::list_blueprints,
            commands::blueprints::create_blueprint,
            commands::blueprints::rename_blueprint,
            commands::blueprints::set_blueprint_pinned,
            commands::blueprints::set_blueprint_archived,
            commands::blueprints::delete_blueprint,
            commands::blueprints::get_blueprint,
            commands::blueprints::add_blueprint_card,
            commands::blueprints::add_blueprint_image_card,
            commands::blueprints::add_blueprint_decorative,
            commands::blueprints::update_blueprint_card,
            commands::blueprints::set_blueprint_card_color,
            commands::blueprints::update_blueprint_node_content,
            commands::blueprints::move_blueprint_node,
            commands::blueprints::resize_blueprint_node,
            commands::blueprints::remove_blueprint_node,
            commands::blueprints::add_blueprint_edge,
            commands::blueprints::update_blueprint_edge_label,
            commands::blueprints::remove_blueprint_edge,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
